/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface EscrowFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "complianceRegistry"
      | "createEscrow"
      | "createEscrowWithGuarantor"
      | "disputeModule"
      | "enforceCompliance"
      | "enforceRiskGuard"
      | "escrows"
      | "guarantorVault"
      | "maxEscrowAmount"
      | "minCollateralBps"
      | "nextEscrowId"
      | "owner"
      | "pause"
      | "paused"
      | "releaseGuarantorCollateral"
      | "renounceOwnership"
      | "riskGuard"
      | "setCollateralConfig"
      | "setComplianceConfig"
      | "setMaxEscrowAmount"
      | "setRiskConfig"
      | "transferOwnership"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CollateralConfigUpdated"
      | "ComplianceConfigUpdated"
      | "EscrowCreated"
      | "MaxEscrowAmountUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "RiskConfigUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "complianceRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createEscrow",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createEscrowWithGuarantor",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      string,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeModule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "enforceCompliance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "enforceRiskGuard",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "escrows",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "guarantorVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxEscrowAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minCollateralBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextEscrowId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "releaseGuarantorCollateral",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "riskGuard", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setCollateralConfig",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setComplianceConfig",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxEscrowAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRiskConfig",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "complianceRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEscrowWithGuarantor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enforceCompliance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enforceRiskGuard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "guarantorVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxEscrowAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minCollateralBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextEscrowId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseGuarantorCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "riskGuard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCollateralConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setComplianceConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxEscrowAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRiskConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace CollateralConfigUpdatedEvent {
  export type InputTuple = [vault: AddressLike, minCollateralBps: BigNumberish];
  export type OutputTuple = [vault: string, minCollateralBps: bigint];
  export interface OutputObject {
    vault: string;
    minCollateralBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplianceConfigUpdatedEvent {
  export type InputTuple = [registry: AddressLike, enforceCompliance: boolean];
  export type OutputTuple = [registry: string, enforceCompliance: boolean];
  export interface OutputObject {
    registry: string;
    enforceCompliance: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowCreatedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    buyer: AddressLike,
    seller: AddressLike,
    escrow: AddressLike
  ];
  export type OutputTuple = [
    escrowId: bigint,
    buyer: string,
    seller: string,
    escrow: string
  ];
  export interface OutputObject {
    escrowId: bigint;
    buyer: string;
    seller: string;
    escrow: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxEscrowAmountUpdatedEvent {
  export type InputTuple = [maxEscrowAmount: BigNumberish];
  export type OutputTuple = [maxEscrowAmount: bigint];
  export interface OutputObject {
    maxEscrowAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskConfigUpdatedEvent {
  export type InputTuple = [guard: AddressLike, enforceRiskGuard: boolean];
  export type OutputTuple = [guard: string, enforceRiskGuard: boolean];
  export interface OutputObject {
    guard: string;
    enforceRiskGuard: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EscrowFactory extends BaseContract {
  connect(runner?: ContractRunner | null): EscrowFactory;
  waitForDeployment(): Promise<this>;

  interface: EscrowFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  complianceRegistry: TypedContractMethod<[], [string], "view">;

  createEscrow: TypedContractMethod<
    [
      seller: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      timeoutAt: BigNumberish,
      evidenceCID: string
    ],
    [[bigint, string] & { escrowId: bigint; escrowAddr: string }],
    "nonpayable"
  >;

  createEscrowWithGuarantor: TypedContractMethod<
    [
      seller: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      timeoutAt: BigNumberish,
      evidenceCID: string,
      guarantor: AddressLike
    ],
    [[bigint, string] & { escrowId: bigint; escrowAddr: string }],
    "nonpayable"
  >;

  disputeModule: TypedContractMethod<[], [string], "view">;

  enforceCompliance: TypedContractMethod<[], [boolean], "view">;

  enforceRiskGuard: TypedContractMethod<[], [boolean], "view">;

  escrows: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  guarantorVault: TypedContractMethod<[], [string], "view">;

  maxEscrowAmount: TypedContractMethod<[], [bigint], "view">;

  minCollateralBps: TypedContractMethod<[], [bigint], "view">;

  nextEscrowId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  releaseGuarantorCollateral: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  riskGuard: TypedContractMethod<[], [string], "view">;

  setCollateralConfig: TypedContractMethod<
    [vault: AddressLike, minBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setComplianceConfig: TypedContractMethod<
    [registry: AddressLike, enforce: boolean],
    [void],
    "nonpayable"
  >;

  setMaxEscrowAmount: TypedContractMethod<
    [maxAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRiskConfig: TypedContractMethod<
    [guard: AddressLike, enforce: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "complianceRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createEscrow"
  ): TypedContractMethod<
    [
      seller: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      timeoutAt: BigNumberish,
      evidenceCID: string
    ],
    [[bigint, string] & { escrowId: bigint; escrowAddr: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createEscrowWithGuarantor"
  ): TypedContractMethod<
    [
      seller: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      timeoutAt: BigNumberish,
      evidenceCID: string,
      guarantor: AddressLike
    ],
    [[bigint, string] & { escrowId: bigint; escrowAddr: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disputeModule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "enforceCompliance"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "enforceRiskGuard"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "guarantorVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "maxEscrowAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minCollateralBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextEscrowId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "releaseGuarantorCollateral"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "riskGuard"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setCollateralConfig"
  ): TypedContractMethod<
    [vault: AddressLike, minBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setComplianceConfig"
  ): TypedContractMethod<
    [registry: AddressLike, enforce: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMaxEscrowAmount"
  ): TypedContractMethod<[maxAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRiskConfig"
  ): TypedContractMethod<
    [guard: AddressLike, enforce: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CollateralConfigUpdated"
  ): TypedContractEvent<
    CollateralConfigUpdatedEvent.InputTuple,
    CollateralConfigUpdatedEvent.OutputTuple,
    CollateralConfigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ComplianceConfigUpdated"
  ): TypedContractEvent<
    ComplianceConfigUpdatedEvent.InputTuple,
    ComplianceConfigUpdatedEvent.OutputTuple,
    ComplianceConfigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowCreated"
  ): TypedContractEvent<
    EscrowCreatedEvent.InputTuple,
    EscrowCreatedEvent.OutputTuple,
    EscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MaxEscrowAmountUpdated"
  ): TypedContractEvent<
    MaxEscrowAmountUpdatedEvent.InputTuple,
    MaxEscrowAmountUpdatedEvent.OutputTuple,
    MaxEscrowAmountUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RiskConfigUpdated"
  ): TypedContractEvent<
    RiskConfigUpdatedEvent.InputTuple,
    RiskConfigUpdatedEvent.OutputTuple,
    RiskConfigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "CollateralConfigUpdated(address,uint16)": TypedContractEvent<
      CollateralConfigUpdatedEvent.InputTuple,
      CollateralConfigUpdatedEvent.OutputTuple,
      CollateralConfigUpdatedEvent.OutputObject
    >;
    CollateralConfigUpdated: TypedContractEvent<
      CollateralConfigUpdatedEvent.InputTuple,
      CollateralConfigUpdatedEvent.OutputTuple,
      CollateralConfigUpdatedEvent.OutputObject
    >;

    "ComplianceConfigUpdated(address,bool)": TypedContractEvent<
      ComplianceConfigUpdatedEvent.InputTuple,
      ComplianceConfigUpdatedEvent.OutputTuple,
      ComplianceConfigUpdatedEvent.OutputObject
    >;
    ComplianceConfigUpdated: TypedContractEvent<
      ComplianceConfigUpdatedEvent.InputTuple,
      ComplianceConfigUpdatedEvent.OutputTuple,
      ComplianceConfigUpdatedEvent.OutputObject
    >;

    "EscrowCreated(uint256,address,address,address)": TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
    EscrowCreated: TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;

    "MaxEscrowAmountUpdated(uint256)": TypedContractEvent<
      MaxEscrowAmountUpdatedEvent.InputTuple,
      MaxEscrowAmountUpdatedEvent.OutputTuple,
      MaxEscrowAmountUpdatedEvent.OutputObject
    >;
    MaxEscrowAmountUpdated: TypedContractEvent<
      MaxEscrowAmountUpdatedEvent.InputTuple,
      MaxEscrowAmountUpdatedEvent.OutputTuple,
      MaxEscrowAmountUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RiskConfigUpdated(address,bool)": TypedContractEvent<
      RiskConfigUpdatedEvent.InputTuple,
      RiskConfigUpdatedEvent.OutputTuple,
      RiskConfigUpdatedEvent.OutputObject
    >;
    RiskConfigUpdated: TypedContractEvent<
      RiskConfigUpdatedEvent.InputTuple,
      RiskConfigUpdatedEvent.OutputTuple,
      RiskConfigUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
